
name: Deploy Website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: docudio

    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Publish
      uses: nogsantos/scp-deploy@master
      with:
        src: ./docudio/*
        host: ${{ secrets.HOST }}
        user: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        remote: "/home/ubuntu"
        port: 22
    - name: ssh to server and do things
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /home/ubuntu
          ls -lart
          sudo pm2 stop docudio
          sudo npm install
          sudo npm run build
          sudo pm2 start npm --name "docudio" --log /var/log/docudio  -- run start

